### ISSUE TITLE
deepeval.models.GeminiModel - model_name does not work in deepeval 3.7.9

### ISSUE THREAD

**Issue by Sliski** [confident-ai/deepeval#2422]
Unable to create GeminiModel  with provided model_name.

**To Reproduce**
following code
```
GeminiModel(
    model_name='gemini-2.5-pro',
    project='<gcp-procject>',
    location='<gcp-location>'
)
```
creates error:
deepeval\models\llms\gemini_model.py:410 in _build_client 
TypeError: Client.__init__() got an unexpected keyword argument 'model_name'

**Expected behavior**
GeminiModel is creaeted and use proper model.

**Comment by penguine-ip** [comment]
Hey @Sliski we have switched to `model` instead of `model_name` for all models: https://deepeval.com/integrations/models/gemini
